name: "First GA"
on: ["push", "issues", "pull_request", "workflow_dispatch"]
run-name: "Expressions & Context by ${{ github.autor }}, event: ${{ github.event_name}}"
jobs:
  show_log:
    runs-on: ubuntu_latest
    steps:
      - name: Show log
        run: echo "Hello World!"
