name: First workflow
on: [push]

jobs:
  show-first-log:
    runs-on: ubuntu-latest
    steps:
      - name: Show some logs
        run: echo "This is my first log"

  show-second-log:
    runs-on: ubuntu-latest
    steps:
      - name: Show some logs
        run: echo "This is my second log"
