name: "First GA"
on: 
  pull_request:
    types: [labeled, synchronize]

run-name: "Expressions, event: ${{ github.event_name}}, action: ${{ github.event.action}} "
jobs:
  show_log:
    runs-on: ubuntu-latest
    steps:
      - name: Show log
        run: echo "Hello World!"

      - name: Show event
        run: echo '${{ github.event }}'

      - name: Show Labels
        run: echo '${{ toJson(github.event.pull_request.labels.*.name) }}'
