name: "First GA"
on: ["push", "pull_request"]

run-name: "Expressions, event: ${{ github.event_name}}, action: ${{ github.action}} "
jobs:
  show_log:
    runs-on: ubuntu-latest
    steps:
      - name: Show log
        run: echo "Hello World!"
      - name: Show Context
        run: echo "${{ toJson(github) }}"
      - name: Show event
        run: echo "${{ toJson(github) }}"
