name: First workflow
on: 
  push:
  pull_request:
    types: 
      - opened
      - syncrhonized
      - labeled
jobs:
  show-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Show Labels
        run: echo '${{ toJson(github) }}'
