name: First workflow
on: ['pull_request', 'issues', 'workflow_dispatch']
jobs:
  show-first-log:
    runs-on: ubuntu-latest
    steps:
      - name: Show some logs
        run: echo "This is my first log"
        
  show-github-global:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.labels.*.name, "bug")
    steps:
      - name: Show Logs
        run: echo 'Hello World!'
