name: First Github Action
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Show log
        run: echo "Hello World!"

      - name: Multiline Command
        run: |
          node -v
          npm -v

