name: First workflow
on: ['pull_request', 'issues']
jobs:
  show-first-log:
    runs-on: ubuntu-latest
    steps:
      - name: Show some logs
        run: echo "This is my first log"
        
  show-github-global:
    runs-on: ubuntu-latest
    steps:
      - name: Show Logs
        run: echo '${{ toJson(github) }}'
        
  show-github-event-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Show Logs
        run: echo '${{ toJson(github.event) }}'
