name: "First GA"
on: ["push", "pull_request"]

run-name: "Expressions & Context by ${{ github.triggering_actor}}, event: ${{ github.event_name}} "
jobs:
  show_log:
    runs-on: ubuntu-latest
    steps:
      - name: Show log
        run: echo "Hello World!"
      - name: Show event
        run: echo '${{ toJson(github.event) }}'
