name: First workflow
on:
  pull_request: 
    types: [synchronize]
jobs:
  show-first-log:
    runs-on: ubuntu-latest
    steps:
      - name: Show some logs
        run: echo "This is my first log"
