name: Workflow Depends
on: 
  pull_request: 
    types: 
      - labeled
  workflow_run:
    workflows: [First workflow]
    types: [completed]
jobs:
  show-log-when-first-ends:
    runs-on: ubuntu-latest
    if: |
      ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Showing workflow is completed
        run: echo "Ha terminado el primer workflow!"
      
