name: Workflow Depends
on: 
  workflow_run:
    workflows: [First workflow]
    types: 
      - completed
jobs:
  show-log-when-first-ends:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hello World!
      
