name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Showing error
        run: echo "::error title=Error title, example-param=Example::Missing semicolon"
      - name: Showing warning
        run: echo "::warning title=Warning title, example-param=Example::Missing semicolon"
