name: Checkout and Display
on: [push]

jobs:
  checkout-and-display:
    runs-on: ubuntu-latest
    steps:
      - name: Display files before checkout
        run: ls -la
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Display files after checkout
        run: ls -la
